require: build/test/setup.js
watch-files:
  - build/**/*
ignore:
  - build/test/unit/**/*
  - build/test/integ/**/*
  - test/,src/,.garden
reporter: spec
timeout: 0
exit: true
spec:
  - build/test/e2e/**/*.js
